# BASE_PATH = ""
# SPARK_BASE_PATH = "/opt/spark/spark-2.4.4-bin-hadoop2.7/bin/spark-submit"
# TEAM_BASE_PATH = "/home/ubuntu/test-bigdata/team/output"
# DATASET_BASE_PATH = "Datasets"
# SETTERS_BASE_PATH = "Setters-Output"

BASE_PATH = "/home/nishant/Documents/sem7/TA/Repo/test-bigdata/adminmgr/sparktestmgr"
SPARK_BASE_PATH = "python"
TEAM_BASE_PATH = "/home/nishant/Documents/TA/Spark/Spark-Outputs"
DATASET_BASE_PATH = "Datasets"
SETTERS_BASE_PATH = "Setters-Output"
