# Generated by Django 2.2.4 on 2019-08-14 14:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 14, 14, 14, 42, 739959, tzinfo=utc)),
        ),
    ]
