# Generated by Django 2.2.4 on 2019-10-30 16:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionMtech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=14)),
                ('file', models.FileField(upload_to='code/Mtech/file')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='a3_full',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SubmissionAssignmentThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('code_file_task_1', models.FileField(upload_to='code/A3/task1')),
                ('code_file_task_2', models.FileField(upload_to='code/A3/task2')),
                ('code_file_task_3', models.FileField(upload_to='code/A3/task3')),
                ('score_1', models.FloatField(default=-1)),
                ('score_2', models.FloatField(default=-1)),
                ('remarks', models.TextField(blank=True, default='None', null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Team')),
            ],
        ),
    ]
