# Generated by Django 2.2.4 on 2019-11-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191030_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionmtech',
            name='usn',
            field=models.CharField(max_length=18),
        ),
    ]
