# Generated by Django 2.2.4 on 2019-08-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190814_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='remarks',
            field=models.TextField(default=None),
        ),
    ]
