# Generated by Django 2.2.4 on 2019-11-26 07:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191103_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='final_project_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FinalProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('code_tar_file', models.FileField(upload_to='code/final')),
                ('remarks', models.TextField(blank=True, default='None', null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Team')),
            ],
        ),
    ]
