# Generated by Django 2.2.4 on 2019-08-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_submission_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='remarks',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
