# Generated by Django 2.2.4 on 2019-08-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190818_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(default='BD_DEFAULT', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
