# Generated by Django 2.2.4 on 2019-09-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190904_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member_3',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
