# Generated by Django 2.2.4 on 2019-09-05 04:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190904_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionassignmentone',
            name='code_config',
            field=models.FileField(storage=api.models.OverwriteStorage(), upload_to='code/config'),
        ),
        migrations.AlterField(
            model_name='submissionassignmentone',
            name='code_file_java_task_1',
            field=models.FileField(blank=True, null=True, storage=api.models.OverwriteStorage(), upload_to='code/java/1'),
        ),
        migrations.AlterField(
            model_name='submissionassignmentone',
            name='code_file_java_task_2',
            field=models.FileField(blank=True, null=True, storage=api.models.OverwriteStorage(), upload_to='code/java/2'),
        ),
        migrations.AlterField(
            model_name='submissionassignmentone',
            name='code_file_java_task_3',
            field=models.FileField(blank=True, null=True, storage=api.models.OverwriteStorage(), upload_to='code/java/3'),
        ),
        migrations.AlterField(
            model_name='submissionassignmentone',
            name='code_file_python_map_1',
            field=models.FileField(blank=True, null=True, storage=api.models.OverwriteStorage(), upload_to='code/python/map1'),
        ),
        migrations.AlterField(
            model_name='submissionassignmentone',
            name='code_file_python_map_2',
            field=models.FileField(blank=True, null=True, storage=api.models.OverwriteStorage(), upload_to='code/python/map2'),
        ),
        migrations.AlterField(
            model_name='submissionassignmentone',
            name='code_file_python_map_3',
            field=models.FileField(blank=True, null=True, storage=api.models.OverwriteStorage(), upload_to='code/python/map3'),
        ),
        migrations.AlterField(
            model_name='submissionassignmentone',
            name='code_file_python_reduce_1',
            field=models.FileField(blank=True, null=True, storage=api.models.OverwriteStorage(), upload_to='code/python/red1'),
        ),
        migrations.AlterField(
            model_name='submissionassignmentone',
            name='code_file_python_reduce_2',
            field=models.FileField(blank=True, null=True, storage=api.models.OverwriteStorage(), upload_to='code/python/red2'),
        ),
        migrations.AlterField(
            model_name='submissionassignmentone',
            name='code_file_python_reduce_3',
            field=models.FileField(blank=True, null=True, storage=api.models.OverwriteStorage(), upload_to='code/python/red3'),
        ),
    ]
