# Generated by Django 2.2.5 on 2019-09-05 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190905_0957'),
        ('api', '0012_auto_20190905_1824'),
    ]

    operations = [
    ]
