# Generated by Django 2.2.4 on 2019-10-06 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20190906_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionAssignmentTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_on', models.DateTimeField(auto_now=True)),
                ('code_file_task_1', models.FileField(upload_to='code/A2/python/task1')),
                ('code_file_task_2', models.FileField(upload_to='code/A2/python/task2')),
                ('score_1', models.IntegerField(default=-1)),
                ('score_2', models.IntegerField(default=-1)),
                ('score_3', models.IntegerField(default=-1)),
                ('score_4', models.IntegerField(default=-1)),
                ('remarks', models.TextField(blank=True, default='None', null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Team')),
            ],
        ),
    ]
