# Generated by Django 2.2.4 on 2019-10-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_submissionassignmenttwo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionassignmenttwo',
            name='score_3',
        ),
        migrations.RemoveField(
            model_name='submissionassignmenttwo',
            name='score_4',
        ),
        migrations.AlterField(
            model_name='submissionassignmenttwo',
            name='score_1',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='submissionassignmenttwo',
            name='score_2',
            field=models.FloatField(default=-1),
        ),
    ]
