# Generated by Django 2.2.4 on 2019-10-10 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_submissionassignmenttwo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionassignmenttwo',
            name='score_3',
        ),
        migrations.RemoveField(
            model_name='submissionassignmenttwo',
            name='score_4',
        ),
    ]
