# Generated by Django 2.2.4 on 2019-10-10 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20191010_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionassignmenttwo',
            name='code_file_task_2',
        ),
    ]
