# Generated by Django 2.2.4 on 2019-10-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_submissionassignmenttwo_code_file_task_2'),
        ('api', '0015_auto_20191010_0951'),
    ]

    operations = [
    ]
